services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php:/var/www/html
    ports:
      - '8080:80'
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=newsletter
    depends_on:
      - mysql
    networks:
      - webinform_network

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: newsletter
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - webinform_network

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    volumes:
      - ./react:/app
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - php
    networks:
      - webinform_network

volumes:
  mysql_data:

networks:
  webinform_network:
    driver: bridge